=head1 palabra 1.8

Copyright 2003 - 2004 Ramiro Gómez. All rights reserved!

This program is offered without warranty of any kind. See the file LICENSE for redistribution terms.

=head1 Summary

Palabra is a web-based dictionary that lets users edit the descriptions of the entries. 
It is written in Perl and uses a MySQL database. Entries are case-sensitive and not censored.
All users can edit descriptions of the chosen word. Descriptions may contain certain HTML-Tags
to structure the content. Disallowed tags are stripped. Users can add translations for existing
words for all available languages.

=head1 Requirements

=over

=item * A web server

=item * MySQL

=item * Perl 5.008 or higher

=item * Perl Modules:

=over

=item * CGI

=item * DBI

=item * DBD::mysql

=item * HTML::Parser

=item * Locale::Maketext

=item * Net::SMTP

=back

=back

=head1 Todo

=over

=item * Edit form HTML check and JavaScript for inserting tags within text

=item * Modularization

=item * I18N, L10N

=item * Error handling

=item * Support for PostgreSQL

=item * Documentation

=item * Generic browse function

=item * Input validation

=item * Statistics

=item * Table Lock

=back

=head1 Known bugs

=over

=item * add_word.cgi no show_index link

=item * index.cgi top_bar no show_index link

=item * edit_word.cgi descriptions may corrupt layout

=item * show_index.cgi show languages instead of translations

=item * contact.cgi show languages instead of translations

=back
